#! /bin/sh

bspc monitor -d I II III IV V

bspc config -m LVDS1 top_padding 18
bspc config border_width         1
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
polybar top -c /home/sven/.config/bspwm/polybar.conf &
